---
title: "CA1"
author: "Jim Coen"
date: "`r format(Sys.Date(), '%A, %B %d, %Y') `"
output:
  pdf_document:
    df_print: kable
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
    highlight:   tango
sansfont: Calibri Light
fontsize: 12pt
documentclass: article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tinytex")
```

# Definitions  
__AI__  
When humans consider the operation of a computer program as exhibiting
intelligence, then that program has Artificial Intelligence.  

__Machine Learning__  
This is a type of Inductive Learning which ‘learns’ the prediction function. It can then make generalizations about new data. The prediction function is a probability estimate.

__Deep Learning__  
In deep learning, the computer program is structured so as to mimic the
human brain. This neural network is a replication of the interconnection
between neurons via dendrites. 

__Parametric and Nonparametric models__  
A parametric learning model simplifies the prediction function to a known
form and uses a fixed set of parameters to characterize the data. It learns the
coefficients of the function from the training data. A non-parametric model
learns the form of the prediction function from training data.  They are a balance between constructing a function that best fits the training data and the ability to generalize.

__Supervised Learning and its components__  
In supervised learning, each observation is type-coded with a ‘label’. For
instance, ‘Spam’, ‘Not Spam’ for email data. Each observation has the same
set of characteristic ‘features’. The algorithm learns the mapping from features
to labels and so can make predictions about new observations. The predicted
output is a probability estimation. Representations include decision trees,
rules and instances. The confusion matrix or ROC curve are evaluation measures for a binary classifier. Gradient descent is one optimization technique.

__Unsupervised Learning and its components__   
Data does not contain
desired outputs or labels. The algorithm must interpret the inherent structure
in the data. It finds clusters of similar feature vectors. It is also used in
dimension reduction in order to transform the feature vectors into a more
concise form. Representations can be clusters or principal components.  Similarity measures evaluate true clusters that do not occur by chance.  Optimization seeks to minimise the variance of feature vectors from the cluster centre.

__Common Types of Errors__   
Errors can occur ‘in-sample’ on training data or ‘out-of-sample’ on new data.  Over-fitting is a
problem that arises when the model is tuned to the training data. Tuning on
the test set gives an incorrect estimate of the accuracy on out-of-sample data.
Error can be due to bias (simplifying assumptions about prediction function)
and to variance (sensitivity of the prediction function to specific sets of
training data).

# Case Study: Online corporate reputation management for a political party.

This study follows the framework described by Rantanen el al[^1] but has a different implementation.

Multi-label Classification [^2]

Types of classifiers:
- Logistic Regression
- SVM
- Random Forests
- Decision Trees


Q2 Please solve the case study (2.5*4=10 marks) (800 words)  
The purpose of this assignment is to build your machine learning project plan. For this exercise, you can
use any one of the example scenarios provided with a completely fictitious example of the problem. You
will be developing a strategic plan for machine learning adoption within this company, and eventually
proposing a structure for a successful machine learning project. You will start by describing your current
overall state of machine learning readiness. You will then explain the business outcome your project is
driving towards, and how business success will be evaluated. You will describe, at a high-level, what
machine learning project you wish to undertake. Finally you will outline the risks of this approach, in
relation to your stage of readiness and the scope of the project.

Select any-one of them  
 You are in the social media division of a political party, and you want to keep better track of the party’s profile and reputation online.  
 You are the head of the Corporate clients division of a major health service provider chain, and you want corporate health applications decided faster and better.  
 You are a software designer and you want to use ML to improve the user experience.  

Answer the following questions
1) Provide a brief description of your company, industry, or business.  
2) What business outcome are you supporting with your machine learning project? How is this outcome relevant and important for the company? How will you evaluate whether the desired outcome is being
achieved?  
3) What machine learning project will you propose to support this business outcome? At a high level, what will your machine learning model be doing? Make the case that this is a viable project (at least in theory) and relates to your overall business goals.  
4) Given the state of readiness you have described and the scope of the project you're proposing, is this a
risky project, broadly speaking? That is, is it appropriate to the stage your company is at or will it provide particular challenges?

Q3 Please write the summary of the journal paper you read and explain about the machine learning techniques you learn from the journal and what are the advantage and disadvantage of the application discussed in the research project.
(800 words) (5 Marks)

Q4 Please also prepare presentation (10- 15 minutes) explaining Answer 2 and Answer 3 in detail. Presentation will be hold on 27-11-2020 on zoom during class.
(20 marks)

[^1]: https://www.emerald.com/insight/content/doi/10.1108/INTR-07-2018-0318/full/html#sec005

[^2]: https://en.wikipedia.org/wiki/Multi-label_classification#Adapted_algorithms